#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    result = ""
    
    #Only the first character of each word should be capitalized.
    #If a word begins with a number, it should not change.
    
    for i in range(len(s)):
        if i == 0 or s[i - 1] == " ":
            result += s[i].upper()
        else:
            result += s[i]
    return result
  
